import { noul, score } from "@typesafe-ai/sdk";
import { getClient, describe } from "./jev";
import type { Candidate, SafetyAudit } from "./types";

/**
 * Agent 3 — Safety Auditor.
 *
 * Asks the two questions that actually matter, from opposite directions:
 * can this come back, and could something unique be lost? Asking both and
 * requiring them to agree catches cases a single question would wave through —
 * a `build/` folder someone committed hand-edited files into, for instance.
 */
export async function audit(
  apiKey: string,
  candidate: Candidate,
): Promise<SafetyAudit> {
  const client = getClient(apiKey);

  const response = await client.systemOne({
    state: describe(candidate),
    questions: {
      regenerable: noul(
        "This directory can be fully regenerated by re-running a standard install or build command, with no loss of the developer's own work.",
      ),
      contains_original_work: noul(
        "This directory could contain hand-written code, configuration, or data that exists nowhere else and could not be recreated.",
      ),
      risk: score("How much damage would permanently deleting this directory cause?", [
        "None — it is pure build output or installed dependencies, recreated automatically on the next build.",
        "Minor — it would have to be reinstalled or rebuilt, costing time and bandwidth but nothing irreplaceable.",
        "Severe — irreplaceable source code, configuration, or personal data would be lost.",
      ]),
    },
  });

  return {
    regenerable: response.answers.regenerable.noul,
    containsOriginalWork: response.answers.contains_original_work.noul,
    risk: response.answers.risk.score,
    riskConfidence: response.answers.risk.confidence,
  };
}
