/** A directory found by the Prospector (Agent 1, Rust). Mirrors `prospector::Candidate`. */
export interface Candidate {
  id: string;
  path: string;
  name: string;
  parent_path: string;
  size_bytes: number;
  file_count: number;
  age_days: number;
  sibling_manifests: string[];
  in_git_repo: boolean;
  depth: number;
}

/** Mirrors `prospector::ScanSummary`. */
export interface ScanSummary {
  root: string;
  candidates: Candidate[];
  total_bytes: number;
  scanned_dirs: number;
  elapsed_ms: number;
  skipped: string[];
}

export type ArtifactKind =
  | "package_deps"
  | "virtual_env"
  | "build_output"
  | "tool_cache"
  | "ide_artifact"
  | "source_code"
  | "user_data";

/** Agent 2 output. */
export interface Classification {
  kind: ArtifactKind;
  confidence: number;
  probabilities: Record<string, number>;
}

/** Agent 3 output. */
export interface SafetyAudit {
  /** P(can be fully regenerated by a standard command). */
  regenerable: number;
  /** P(contains work that exists nowhere else). */
  containsOriginalWork: number;
  /** Expected damage, 0 (none) to 2 (severe). */
  risk: number;
  riskConfidence: number;
}

/** Agent 4 output. */
export interface Reconstruction {
  /** P(a manifest nearby proves the restore command). */
  restorable: number;
  /** P(this belongs to an actively-worked project). */
  activelyInUse: number;
  /** The command we believe would rebuild this, derived from manifests. */
  restoreCommand: string | null;
}

export type Verdict = "safe" | "review" | "keep";

/** The full decision for one candidate, with every agent's reasoning retained. */
export interface Assessment {
  candidate: Candidate;
  classification: Classification;
  safety: SafetyAudit;
  reconstruction: Reconstruction;
  /** Combined 0–1 safety score that drives the gate. */
  score: number;
  verdict: Verdict;
  /** Human-readable justification, shown in the UI. Never hidden. */
  rationale: string;
  error?: string;
}

export interface ReclaimRequestItem {
  path: string;
  bytes: number;
}

export interface ReclaimOutcome {
  path: string;
  bytes: number;
  ok: boolean;
  error: string | null;
}

export interface ReclaimReport {
  receipt_id: string;
  timestamp: number;
  outcomes: ReclaimOutcome[];
  bytes_reclaimed: number;
  succeeded: number;
  failed: number;
  receipt_path: string | null;
  dry_run: boolean;
}
